apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "instana"
spec:
  templates:
    - name: clickhouse
      spec:
        imagePullSecrets:
          - name: clickhouse-image-secret
