apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - path: postgres-scc-patch.yaml
    target:
      kind: SecurityContextConstraints
      name: postgres-scc

resources:
  - ../base