apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - path: cassandra-scc-patch.yaml
#    target:
#      kind: SecurityContextConstraints
#      name: cassandra-scc

resources:
  - ../base